# Site settings
title: Leorowe's Blog
email: leorowe.wei@gmail.com
description: "Here is my personal blog that record my daily life thought and some funny experience"
baseurl: ""
url: "http://weibo.com/leorowe"
twitter_username: leorowe_wei
github_username:  Leorowe

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
excerpt_separator: "\n\n"

#set encode
encoding: UTF-8
